services:
  app:
    image: franzensfestegibsnet:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
    ports:
      - "9000:8000"
    networks:
      - backend
      - frontend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: franzensfestegibsnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
  frontend:
